
services:
  social-media-blog:
    build: .
    container_name: mindtype-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "src.social_media_blog.app:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
